import Anthropic from '@anthropic-ai/sdk';
import { AiProvider, AiWorkflowResult, AiExplanationResult } from './provider.js';
import { logger } from './logger.js';
import { WorkflowPayload } from '../schemas/workflowSchema.js';

export class ClaudeProvider implements AiProvider {
  private client: Anthropic;
  private modelId: string;

  constructor(apiKey?: string, modelId: string = 'claude-3-5-sonnet-20241022') {
    this.client = new Anthropic({
      apiKey: apiKey || process.env.ANTHROPIC_API_KEY,
    });
    this.modelId = modelId;
  }

  async createWorkflowDraft(
    prompt: string,
    context?: { existingWorkflow?: WorkflowPayload; nodeCatalog?: string[] }
  ): Promise<AiWorkflowResult> {
    try {
      const systemPrompt = this.buildSystemPrompt();
      const fullPrompt = this.buildFullPrompt(prompt, context);

      const response = await this.client.messages.create({
        model: this.modelId,
        max_tokens: 4096,
        system: systemPrompt,
        messages: [{ role: 'user', content: fullPrompt }],
      });

      const content = response.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response content type from Claude');
      }

      const payload = this.parsePayload(content.text);
      return { payload, summary: payload.metadata?.summary || 'Workflow generated by Claude' };
    } catch (error) {
      logger.error('Claude workflow generation failed', {
        error: error instanceof Error ? error.message : String(error),
        provider: 'claude',
      });
      throw error;
    }
  }

  async modifyWorkflowDraft(
    prompt: string,
    currentWorkflow: WorkflowPayload,
    context?: { conversationHistory?: string[] }
  ): Promise<AiWorkflowResult> {
    try {
      const systemPrompt = this.buildSystemPrompt();
      const fullPrompt = `Current workflow: ${JSON.stringify(currentWorkflow, null, 2)}

Modification request: ${prompt}

Please return the modified workflow as valid JSON with the same structure.`;

      const response = await this.client.messages.create({
        model: this.modelId,
        max_tokens: 4096,
        system: systemPrompt,
        messages: [{ role: 'user', content: fullPrompt }],
      });

      const content = response.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response content type from Claude');
      }

      const payload = this.parsePayload(content.text);
      return { payload, summary: payload.metadata?.summary || 'Workflow modified by Claude' };
    } catch (error) {
      logger.error('Claude workflow modification failed', {
        error: error instanceof Error ? error.message : String(error),
        provider: 'claude',
      });
      throw error;
    }
  }

  async explainWorkflow(currentWorkflow: WorkflowPayload): Promise<AiExplanationResult> {
    try {
      const prompt = `Explain the following workflow in plain language:

${JSON.stringify(currentWorkflow, null, 2)}

Provide a clear, concise explanation of what this workflow does and how it works.`;

      const response = await this.client.messages.create({
        model: this.modelId,
        max_tokens: 2048,
        messages: [{ role: 'user', content: prompt }],
      });

      const content = response.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response content type from Claude');
      }

      return { explanation: content.text };
    } catch (error) {
      logger.error('Claude workflow explanation failed', {
        error: error instanceof Error ? error.message : String(error),
        provider: 'claude',
      });
      throw error;
    }
  }

  private buildSystemPrompt(): string {
    return `You are an expert workflow designer AI assistant. Your task is to generate, modify, and explain workflow configurations.

When generating workflows:
1. Create valid JSON with "nodes" array and "triggers" array
2. Each node should have: id, type, name, config (arbitrary properties), next (optional), conditions (optional)
3. Ensure nodes have valid structure matching the WorkflowPayload schema
4. Validate no circular dependencies exist
5. Return ONLY valid JSON, no markdown formatting

Always respond with properly formatted JSON that can be parsed directly.`;
  }

  private buildFullPrompt(
    prompt: string,
    context?: { existingWorkflow?: WorkflowPayload; nodeCatalog?: string[] }
  ): string {
    const lines = [prompt];

    if (context?.existingWorkflow) {
      lines.push(
        `\nExisting workflow JSON: ${JSON.stringify(context.existingWorkflow)}`
      );
    }

    return lines.join('\n');
  }

  private parsePayload(text: string): WorkflowPayload {
    const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    const jsonString = jsonMatch ? jsonMatch[1].trim() : text.trim();

    try {
      return JSON.parse(jsonString) as WorkflowPayload;
    } catch (error) {
      logger.error('Failed to parse Claude response as JSON', {
        response: text.substring(0, 500),
        error: error instanceof Error ? error.message : String(error),
      });
      throw new Error(`Invalid JSON response from Claude: ${error}`);
    }
  }
}
